name: lotus
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
#  device_preview:
  carousel_slider:
  flutter_verification_code:
  get:
  get_storage:
  permission_handler:
  barcode_scan:
  image_picker:
  flutter_rating_bar:
  google_maps_flutter:
  geolocator:
  dio:
  geocoder:
  firebase_messaging:
  firebase_analytics:
  connectivity:
  flutter_local_notifications:
  firebase_auth:
  sms_autofill:
  firebase_core:
  pin_code_fields:
  flare_flutter:
dev_dependencies:
  flutter_native_splash:
  flutter_test:
    sdk: flutter

# For information on the gejikneric Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/img/
    - assets/img/icons/

  # An image asset can refer to one or more resgeolocatorolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: cairo_black
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
    - family: cairo_bold
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
    - family: cairo_light
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
    - family: cairo_extra_light
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
    - family: cairo_regular
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: cairo_semibold
      fonts:
        - asset: assets/fonts/Cairo-SemiBold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages